name: Workflow2 - Post Validation Tasks
on:
  workflow_run:
    workflows: ["Workflow1"]      # Match the name of your main workflow
    types:
      - completed                 # Trigger only when Workflow1 is completed

jobs:
  process_results:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Additional Tasks
        run: echo "Additional steps can be added here."
      - name: Generate Markdown Report
        run: |
          echo "### 🚀 **Code Validation Results** 🚀" > comment.md
          echo "" >> comment.md
          echo "| Workflow Name | Status | Details |" >> comment.md
          echo "|---------------|--------|---------|" >> comment.md  
      - name: Post Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment.md
          token: ${{ secrets.GITHUB_TOKEN }}  
