name: Workflow2 - Post Validation Tasks

on:
  workflow_run:
    workflows: ["Workflow1"]      # Match the name of your main workflow
    types:
      - completed                 # Trigger only when Workflow1 is completed
    branches:
      - main                      # Optional: Trigger only on the main branch

jobs:
  process_results:
    runs-on: ubuntu-latest
    steps:
      - name: Download Workflow1 Artifacts
        uses: actions/download-artifact@v3
        with:
          name: workflow-1-results  # Match the artifact name from Workflow1
          path: .

      - name: Display Validation Results
        run: cat result.txt         # Process or display the results from Workflow1

      - name: Perform Additional Tasks
        run: echo "Additional steps can be added here."


