name: Triggered Workflow Example

on:
  workflow_run:
    workflows: [Workflow1]      # Name of the triggering workflow
    types: 
      - completed                     # Runs only when the workflow is completed
    branches:
      - main                          # Specifies the branch to watch (optional)

jobs:
  post_completion_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run a task after main workflow
        run: echo "Main workflow has completed! Running post-completion tasks."

