name: Combine and Comment Results
on:
  workflow_run:
    workflows: [Workflow1]
    types:
      - completed

jobs:
  combine_results:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./results

      - name: Combine Results
        run: |
          cat ./results/workflow-1-results/result.txt > combined.txt
          echo "------" >> combined.txt
