name: Workflow2
on:
  pull_request:
    branches:
      - main
jobs:
  append_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find and Append to Latest Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the latest comment
          LATEST_COMMENT=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments --paginate | jq -c '.[-1]')
          
          # Extract comment ID and body
          COMMENT_ID=$(echo "$LATEST_COMMENT" | jq -r .id)
          COMMENT_BODY=$(echo "$LATEST_COMMENT" | jq -r .body)

          # Check if the latest comment contains the tag
          if [[ "$COMMENT_BODY" == *"[WorkflowCommentTag]"* ]]; then
            # Append new content to the comment
            UPDATED_BODY="${COMMENT_BODY}
            Second Comment"
            gh api repos/${{ github.repository }}/issues/comments/$COMMENT_ID -X PATCH -f body="$UPDATED_BODY"
          else
            echo "The latest comment does not contain the tag '[WorkflowCommentTag]'. Exiting."
          fi

